### ISSUE TITLE
rejectAuthorization = false

### ISSUE THREAD

**Issue by joshheil** [dhermes/tls-codelab#2]
In your one example you set rejectAuthorization to false which from my understanding will leave the application open to a MITM attack.  If you leave it false, it would not be considered mTLS because both sides wouldn't not be verifying each other before beginning the communication.

**Comment by dhermes** [comment]
@joshheil Thanks for stopping by! Are you referring to https://github.com/dhermes/tls-codelab/blob/a397c8ae732ab8e490998ef96269ce57362ad0a0/docs/nodejs/server-mtls.js#L48?

Also, if you don't mind my asking, how did you discover this repo?

**Comment by joshheil** [comment]
Yes! I actually first saw your code from this link in Google: https://blog.bossylobster.com/tls-codelab/mutual-tls.html

I was researching mTLS and trying to understand what I need to set-up for one of my projects.

**Comment by dhermes** [comment]
Gotcha. Yeah so `server-mtls.js` is not intended to be a production-ready configuration.

The the actual handler [checks][1] if `req.client.authorized` is truthy and returns `{"mTLSValid": true}` in that case. The whole reason I set `rejectUnauthorized: false` was so that in the **unauthorized** case I could give a helpful error message: `'{"mTLSValid": false, "reason": ' + JSON.stringify(reason) + '}`.

E.g. on the page you linked the response comes back as:

```
$ curl --cacert ../tls-certs/root-ca-cert.pem https://localhost:9443
{"mTLSValid": false, "reason": "UNABLE_TO_GET_ISSUER_CERT"}
```

(as opposed to a non-HTTP error due to the TLS handshake failing if `rejectUnauthorized: true` was set)

----

I am going to pre-emptively close this issue because I think I've covered the question. If you'd like to re-open let me know and I'm happy to keep chatting.

[1]: https://github.com/dhermes/tls-codelab/blob/a397c8ae732ab8e490998ef96269ce57362ad0a0/docs/nodejs/server-mtls.js#L58-L61
